### PR TITLE
#8 #20 - Fix infinity-norm; rename to opnorm; add 1-norm

### LINKED ISSUE #8: Faster infinity-norm computation
Currently the computation of the infinity norm uses `left` and `right`:
https://github.com/JuliaReach/IntervalMatrices.jl/blob/a0247824cc9a907259a0a00d6c55275fc3bc5a74/src/matrix.jl#L53

However, these methods allocate one new vector (of the size of the matrix) each. Since in the end we are only interested in a single value, this is not necessary.

```julia
function infinity_norm(A)
    res = abs(A[1, 1].left)
    for itv in A
        res = max(res, abs(itv.left), itv.right)
    end
    return res
end
```

(Note that I omitted the `abs` on `itv.right` for efficiency.)

We should also evaluate if the following is faster (rationale: write only when necessary).

```julia
function infinity_norm2(A)
    res = abs(A[1, 1].left)
    for itv in A
        m = max(abs(itv.left), itv.right)
        if m > res
            res = m
        end
    end
    return res
end
```

### LINKED ISSUE #20: Rename norm to opnorm

### PR DESCRIPTION
**Pull request by schillic**
Closes #8.
Closes #20.

### CODE REVIEW

**Comment by mforets** [comment]
In v1.0 or higher we should actually have as the baseline implementation:

```julia
function LinearAlgebra.opnorm(A::IntervalMatrix, p::Real=Inf)
    if p == Inf
        return LinearAlgebra.opnorm(max.(abs.(left(A)), abs.(right(A))), p)
    else
        error("the interval matrix norm for p=$p is not implemented")
    end
end
```

File: src/matrix.jl [hunk 1]
```diff
@@ -48,9 +48,23 @@ The matrix norm of an interval matrix.
...
-        return LinearAlgebra.norm(max.(abs.(left(A)), abs.(right(A))), Inf)
+        # for p=Inf, the operator norm is the maximum absolute row sum
+        res = 0
+        for i in axes(A, 1)
+            res = max(res, sum(max(abs(itv.left), itv.right)
+                               for itv in view(A, i, :)))
+        end
+        return res
+    elseif p == 1
+        # for p=Inf, the operator norm is the maximum absolute column sum
```
Comment (mforets) [inline src/matrix.jl]:
```suggestion
        # for p=1, the operator norm is the maximum absolute column sum
```

File: src/matrix.jl [hunk 2]
```diff
@@ -48,9 +48,23 @@ The matrix norm of an interval matrix.
...
 - `p` -- (optional, default: `Inf`): the class of `p`-norm
 """
-function LinearAlgebra.norm(A::IntervalMatrix, p::Real=Inf)
+function LinearAlgebra.opnorm(A::IntervalMatrix, p::Real=Inf)
     if p == Inf
-        return LinearAlgebra.norm(max.(abs.(left(A)), abs.(right(A))), Inf)
+        # for p=Inf, the operator norm is the maximum absolute row sum
+        res = 0
+        for i in axes(A, 1)
+            res = max(res, sum(max(abs(itv.left), itv.right)
```
Comment (mforets) [inline src/matrix.jl]: seems to me that `abs` should also be applied as well to the right part of `itv`, or not?

File: src/matrix.jl [hunk 3]
```diff
@@ -48,9 +48,23 @@ The matrix norm of an interval matrix.
 - `A` -- interval matrix
 - `p` -- (optional, default: `Inf`): the class of `p`-norm
 """
-function LinearAlgebra.norm(A::IntervalMatrix, p::Real=Inf)
+function LinearAlgebra.opnorm(A::IntervalMatrix, p::Real=Inf)
     if p == Inf
-        return LinearAlgebra.norm(max.(abs.(left(A)), abs.(right(A))), Inf)
+        # for p=Inf, the operator norm is the maximum absolute row sum
+        res = 0
```
Comment (mforets) [inline src/matrix.jl]: We can use  `zero(N)` with `N` taken from the numerical field of `A::IntervalMatrix`.
