### PR TITLE
#101 - Undef initializer 

### LINKED ISSUE #101: Undef initializer
```julia
julia> Matrix{Float64}(undef, 2, 2)
2×2 Array{Float64,2}:
 6.93301e-310  0.0
 6.93303e-310  0.0

julia> IntervalMatrix(undef, 2, 2)
ERROR: MethodError: no method matching IntervalMatrix(::UndefInitializer, ::Int64, ::Int64)
Closest candidates are:
  IntervalMatrix(::UniformScaling{Interval{T}}, ::Any, ::Any) where T at /home/mforets/.julia/dev/IntervalMatrices/src/matrix.jl:46
  IntervalMatrix(::UniformScaling{Interval{T}}, ::Any) where T at /home/mforets/.julia/dev/IntervalMatrices/src/matrix.jl:46
Stacktrace:
 [1] top-level scope at REPL[13]:1
```
If we add the following method:

```julia
function IntervalMatrix{T}(u::UndefInitializer, n, m) where {T}
    mat = Matrix{Interval{T}}(undef, n, m)
    return IntervalMatrix(mat)
end
```
then:

```julia
julia> IntervalMatrix{Float64}(undef, 2, 2)
2×2 IntervalMatrix{Float64,Interval{Float64},Array{Interval{Float64},2}}:
 [6.933e-310, 6.93304e-310]    [6.93303e-310, 6.93304e-310]
 [6.93303e-310, 6.93304e-310]  [6.93303e-310, 6.93304e-310]
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #101.

Requires:

- [x] Add test.
- [x] Add to docs.

### CODE REVIEW

**Comment by mforets** [comment]
With this constructor some patterns are simplified, eg.

```julia
function rand(::Type{IntervalMatrix}, m::Int=2, n::Int=2;
              N=Float64, rng::AbstractRNG=GLOBAL_RNG)
    B = Matrix{Interval{N}}(undef, m, n)
    for j in 1:n
        for i in 1:m
            @inbounds B[i, j] = _rand_interval(N=N, rng=rng)
        end
    end
    return IntervalMatrix(B)
end
```

becomes
```julia
function rand(::Type{IntervalMatrix}, m::Int=2, n::Int=2;
              N=Float64, rng::AbstractRNG=GLOBAL_RNG)
    B = IntervalMatrix{N}(undef, m, n)
    for j in 1:n
        for i in 1:m
            @inbounds B[i, j] = _rand_interval(N=N, rng=rng)
        end
    end
    return B
end
```

File: src/matrix.jl [hunk 1]
```diff
@@ -41,6 +41,12 @@ getindex(M::IntervalMatrix, i::Int) = getindex(M.mat, i)
 setindex!(M::IntervalMatrix, X, inds...) = setindex!(M.mat, X, inds...)
 copy(M::IntervalMatrix) = IntervalMatrix(copy(M.mat))
 
+# undef initializer, eg. IntervalMatrix{Float64}(undef, 2, 2)
+function IntervalMatrix{T}(u::UndefInitializer, m, n) where {T}
```
Comment (schillic) [inline src/matrix.jl]:
```suggestion
function IntervalMatrix{T}(u::UndefInitializer, m, n=m) where {T}
```
